project:
  type: website

website:
  title: "PP2024"
  navbar:
    right:
      - icon: github
        href: https://github.com/amondmomo/PP2024
      
format:
  html:
    theme: cosmo
    css: styles.css